#!/bin/bash
#
# TestInstallRSIND.bash - test and then (if OK) install a new RSIND file for use by the appropriate
#   applications.
#
# This script is executed with two required arguments:
#   $1:  the (simple) name of the newly uploaded RSIND file
#   $2:  the season being processed
#
# Exit Status:
#   0 - file uploaded and copied to destination directories correctly.
#   1 - there was a problem and the file was NOT uploaded to any destination directory
#   2 - the file already existed in at least one of the destination directories so it was not
#       re-copied.  It was copied to whatever directories didn't already have the file.
#
# Copyright (c) 2019 Bob Upshaw.  This software is covered under the Open Source MIT License 


# todo:  remove really really old RSIND files from destdir
#   ...  remove really really old files from UPLOAD dirs.
#   ...  remove really really old log files
#   ...  remove TEMP_FILE

#set -x

TEMP_FILE=/tmp/TestInstallRSIND.$$
SIMPLE_SCRIPT_NAME=`basename $0`
# compute the full path name of the directory holding this script.  We'll find
# other files we need using this path:
SCRIPT_DIR=$(dirname $0)
cd $SCRIPT_DIR
SCRIPT_DIR=`pwd -P`

# calculate today's date and a few other dates for this season:
TODAY_MD=$(date +"%m%d")        # today's date in form MMDD, e.g. 0513 for May 13
OCT15_MD="1015"                 # Oct 15 in above format
JUN1_MD="0601"                  # June 1 in above format

# USMS allows members to register for NEXT season starting Nov 1 of THIS season.  We care about this because
# we want THIS season's AGSOTY and OW competitors to be registered for THIS season.  We will use NEXT season's registration
# for AGSOTY and OW but we definately don't want o use ONLY NEXT season's registrations to determine OW and AGSOTY
# points for THIS season.
GOT_NEXT_SEASONS_RSIND=0          # set to 1 if we think the newly uploaded RSIND file contains next season's registrations only

function Usage {
    echo "Usage: $0 RSIND_file_name Season_being_processed"
    echo "    (e.g. TestInstallRSIND.bash \"USMS-RSIND_03-11-2019 (1).csv\"   2019  )"
}

# did we get the RSIND file name and season?
RSIND_FILE_NAME="$1"        # simple name of newly uploaded RSIND file - we may change it below
ORIGINAL_RSIND_FILE_NAME=$RSIND_FILE_NAME       # remember the original name in case we need to change it
SEASON_BEING_PROCESSED="$2"
if [ .$SEASON_BEING_PROCESSED = . ] ; then
    echo "ERROR: Missing Season Being Processed.  Abort!"
    Usage;
    exit 1;
fi

if [ $SEASON_BEING_PROCESSED -lt 2019 ] || [ $SEASON_BEING_PROCESSED -gt 2030 ] ; then
    echo "ERROR: Invalid Season Being Processed (must be 2019 <= Season <= 2030).  Abort!"
    Usage;
    exit 1;
fi

# compute the season for "next season" - used if we have to populate next season's AGSOTY, too
NEXT_SEASON_TO_BE_PROCESSED=$(( SEASON_BEING_PROCESSED + 1 ))

# go to the directory containing the uploaded RSIND file that we want to use (if OK)
pushd /usr/home/pacdev/Automation/Upload/UploadedFiles/RSIND 2>&1 >/dev/null
UPLOADED_RSIND_DIR=`pwd -P`
FULL_RSIND_FILE_NAME="$UPLOADED_RSIND_DIR/$RSIND_FILE_NAME"
if [[ ! -r "$RSIND_FILE_NAME" ]] ; then
    echo "ERROR: The uploaded RSIND file is not readable.  Abort!"
    echo "(((ERROR: '$FULL_RSIND_FILE_NAME' is not readable.)))"
    exit 1;
fi
popd 2>&1 >/dev/null
# cwd is now SCRIPT_DIR

# calculate the size of the newly uploaded RSIND file
NUM_ROWS_IN_NEW_RSIND_FILE=`wc -l <"$FULL_RSIND_FILE_NAME"`

# compute destination AGSOTY directory and size of current RSIND file:
DESTDIR=$SCRIPT_DIR/../../../PMSTopTen/SeasonData/Season-$SEASON_BEING_PROCESSED/PMSSwimmerData
FULL_DEST_FILE=$DESTDIR/$RSIND_FILE_NAME
# get the size of the RSIND file in this directory:
EXISTING_RSIND_SIZE=0
EXISTING_RSIND_FILE=`$SCRIPT_DIR/GetMostRecentVersion.pl '^(.*RSIND.*)|(.*RSIDN.*)$' $DESTDIR`
STATUS_GetMostRecentVersion=$?
if [ $STATUS_GetMostRecentVersion -eq 0 ] ; then
    EXISTING_RSIND_SIZE=`wc -l <"$DESTDIR/$EXISTING_RSIND_FILE"`
fi


#####
#####  Modify newly uploaded RSIND file if necessary
#####


USER_MESSAGE=
DROP_MESSAGE=
HIDDEN_MESSAGE=
WARNING_STRINGS=

# we need to be careful near the end of the season.  On Nov 1 when an RSIND file is generated by the PMS administrator
# the results generated by USMS give registrations for NEXT season only!  So between Nov 1 and Dec 31 when we get
# an RSIND file we need to MERGE it with the previous one.  The exact rules for merging are given with that code.
# Because we have no control on how USMS works we'll be conserative and start looking for the change to next season's
# RSIND file earlier than Nov 1.  We'll detect it by comparing the size of the newly uploaded RSIND file with the
# previous RSIND file, and if it's "significantly" smaller we'll assume we have next season's RSIND file.
# The "previous" RSIND file will be taken from the AGSOTY files.
if [ $TODAY_MD > $OCT15_MD ] ; then
    # This could be an RSIND file for NEXT season only!
    if [ $STATUS_GetMostRecentVersion -eq 0 ] && [ $NUM_ROWS_IN_NEW_RSIND_FILE < $((EXISTING_RSIND_SIZE - 100 )) ] ; then
        # The newly uploaded file is significantly smaller than the previous RSIND file, so we're going to
        # assume that the newly uploaded file is for next season ONLY!  Merge the new file with the old one:
        GOT_NEXT_SEASONS_RSIND=1
        MERGE_SIMPLE_NAME=MergeRSINDFiles
        MERGE_PROG=$SCRIPT_DIR/../$MERGE_SIMPLE_NAME.pl
        # Since we are constructing a different uploaded RSIND file that is different from the one the user uploaded
        # we are going to change its name:
        RSIND_FILE_NAME=Merged_$RSIND_FILE_NAME
        MERGED_FULL_RSIND_FILE_NAME=$UPLOADED_RSIND_DIR/$RSIND_FILE_NAME
        $MERGE_PROG "$DESTDIR/$EXISTING_RSIND_FILE" $FULL_RSIND_FILE_NAME $SEASON_BEING_PROCESSED \
            > $MERGED_FULL_RSIND_FILE_NAME
        # the "new" uploaded RSIND file is now named "Merged_xxx", where "xxx" is the name of the newly
        # uploaded RSIND file supplied by the user.
        FULL_RSIND_FILE_NAME=$MERGED_FULL_RSIND_FILE_NAME
        DROP_MESSAGE=$DROP_MESSAGE "<br>MERGED '$ORIGINAL_RSIND_FILE_NAME' with '$EXISTING_RSIND_FILE' and installed $RSIND_FILE_NAME instead."
    # else the newly uploaded RSIND file is the one we want
    fi
# else it's pretty early in the season - assume the newly uploaded RSIND file is the one we want
fi



#####
#####  VALIDATION
#####


# analyze the RSIND file before we copy it
VALIDATE_SIMPLE_NAME=ValidateNewRSINDFile
VALIDATE_PROG=$SCRIPT_DIR/../$VALIDATE_SIMPLE_NAME.pl
VALIDATE_LOG_DIR=$SCRIPT_DIR/../Logs/
mkdir -p $VALIDATE_LOG_DIR
VALIDATE_LOG=$VALIDATE_LOG_DIR${VALIDATE_SIMPLE_NAME}Log-$SEASON_BEING_PROCESSED.txt
rm -f $VALIDATE_LOG
$VALIDATE_PROG "$FULL_RSIND_FILE_NAME" $SEASON_BEING_PROCESSED 2>&1 >$TEMP_FILE
if [ ! -e $VALIDATE_LOG ] ; then
    echo "Unable to execute $VALIDATE_SIMPLE_NAME - RSIND file not installed!"
    echo "(((prog: $VALIDATE_PROG , log: $VALIDATE_LOG, stderr/out: $TEMP_FILE)))"
    exit 1
fi
NUM_ERRORS=`grep -c '! ERROR' $VALIDATE_LOG`
NUM_WARNINGS=`grep -c '! WARNING' $VALIDATE_LOG`
if [ $NUM_ERRORS -gt 0 ] ; then
    ERROR_STRINGS=`grep '! ERROR' $VALIDATE_LOG`
    echo "$NUM_ERRORS errors discovered - RSIND file not installed!"
    echo "[[[$ERROR_STRINGS]]]"
    echo "(((See $VALIDATE_LOG for more details)))"
    exit 1;
fi

NUM_ROWS_IN_NEW_RSIND_FILE=`wc -l <"$FULL_RSIND_FILE_NAME"`
EXIT_STATUS=0
if [ $NUM_WARNINGS -gt 0 ] ; then
    WARNING_STRINGS=`grep '! WARNING' $VALIDATE_LOG`
    USER_MESSAGE="$USER_MESSAGE $NUM_WARNINGS warnings discovered"
 #   DROP_MESSAGE="[[[$DROP_MESSAGE $WARNING_STRINGS]]]"
    HIDDEN_MESSAGE="(((See $VALIDATE_LOG for more details)))"
fi


#####
#####  AGSOTY
#####

# If all ok copy the newly uploaded RSIND file to the appropriate AGSOTY directory:
if [ -e "$FULL_DEST_FILE" ] ; then
    # huh?  somehow this file already exists at the destination - refuse to copy it again.
    USER_MESSAGE="$USER_MESSAGE; This file already exists for AGSOTY"
    DROP_MESSAGE="$DROP_MESSAGE <br>$FULL_DEST_FILE already exists for AGSOTY - not copied again."
    HIDDEN_MESSAGE="$HIDDEN_MESSAGE; ((('cp -n $FULL_RSIND_FILE_NAME $DESTDIR' failed))); "
    EXIT_STATUS=2
else
    # do the copy!
    if cp -n "$FULL_RSIND_FILE_NAME" $DESTDIR ; then
        DROP_MESSAGE="$DROP_MESSAGE <br>$RSIND_FILE_NAME ($NUM_ROWS_IN_NEW_RSIND_FILE rows) copied " \
                     "successfully for $SEASON_BEING_PROCESSED AGSOTY"
        if [ $STATUS_GetMostRecentVersion -eq 0 ] ; then
            DROP_MESSAGE="$DROP_MESSAGE <br>   --Replacing $EXISTING_RSIND_FILE ($EXISTING_RSIND_SIZE rows)"
        else
            DROP_MESSAGE="$DROP_MESSAGE <br>   --(There was no prior RSIND file.)"
        fi
        HIDDEN_MESSAGE="$HIDDEN_MESSAGE; (((Copied to $DESTDIR for $SEASON_BEING_PROCESSED AGSOTY))); "
        # Yet another special case:  If it's past June 1 then the next season's SCY season has started.  We will
        # have to also copy this AGSOTY file to that season's AGSOTY directory too...
        if [ $TODAY_MD >= $JUN1_MD ] ; then
            DESTDIR=$SCRIPT_DIR/../../../PMSTopTen/SeasonData/Season-$NEXT_SEASON_TO_BE_PROCESSED/PMSSwimmerData
            mkdir -m go-rwx -p $DESTDIR
            FULL_DEST_FILE=$DESTDIR/$RSIND_FILE_NAME
            if cp -n "$FULL_RSIND_FILE_NAME" $DESTDIR ; then
                DROP_MESSAGE="$DROP_MESSAGE <br>$RSIND_FILE_NAME ($NUM_ROWS_IN_NEW_RSIND_FILE rows) copied " \
                     "successfully for $NEXT_SEASON_TO_BE_PROCESSED AGSOTY"
                if [ $STATUS_GetMostRecentVersion -eq 0 ] ; then
                    DROP_MESSAGE="$DROP_MESSAGE <br>   --Replacing $EXISTING_RSIND_FILE ($EXISTING_RSIND_SIZE rows)"
                else
                    DROP_MESSAGE="$DROP_MESSAGE <br>   --(There was no prior RSIND file.)"
                fi
                HIDDEN_MESSAGE="$HIDDEN_MESSAGE; (((Copied to $DESTDIR for $NEXT_SEASON_TO_BE_PROCESSED AGSOTY))); "
            else
                USER_MESSAGE="$USER_MESSAGE; Failed to cp $RSIND_FILE_NAME for $NEXT_SEASON_TO_BE_PROCESSED AGSOTY"
                HIDDEN_MESSAGE="$HIDDEN_MESSAGE; ((('cp -n $FULL_RSIND_FILE_NAME $DESTDIR' failed))); "
                EXIT_STATUS=1
            fi
        fi
    else
        USER_MESSAGE="$USER_MESSAGE; Failed to cp $RSIND_FILE_NAME for $SEASON_BEING_PROCESSED AGSOTY"
        HIDDEN_MESSAGE="$HIDDEN_MESSAGE; ((('cp -n $FULL_RSIND_FILE_NAME $DESTDIR' failed))); "
        EXIT_STATUS=1
    fi
fi



#####
#####  Open Water
#####

# (sigh...)  Yet another special case!  We will install the newly uploaded RSIND file for OW ONLY if it is earlier
# than Oct 15.  This is based on past history:  the OW season is finished by mid-late September.
# In addition, if the newly uploaded RSIND file is NEXT season's file we definately DO NOT want to use it for
# this season's OW.
if [ $TODAY_MD < $OCT15_MD ] && [ $GOT_NEXT_SEASONS_RSIND == 0 ] ; then
    # compute destination OW directory:
    DESTDIR=$SCRIPT_DIR/../../../PMSOWPoints/SourceData/PMSSwimmerData/
    FULL_DEST_FILE=$DESTDIR/$RSIND_FILE_NAME
    # get the size of the RSIND file in this directory:
    EXISTING_RSIND_SIZE=0
    EXISTING_RSIND_FILE=`$SCRIPT_DIR/GetMostRecentVersion.pl '^(.*RSIND.*)|(.*RSIDN.*)$' $DESTDIR`
    STATUS_GetMostRecentVersion=$?
    if [ $STATUS_GetMostRecentVersion -eq 0 ] ; then
        EXISTING_RSIND_SIZE=`wc -l <"$DESTDIR/$EXISTING_RSIND_FILE"`
    fi
    if [ -e "$FULL_DEST_FILE" ] ; then
        # huh?  somehow this file already exists at the destination - refuse to copy it again.
        USER_MESSAGE="$USER_MESSAGE; This file already exists for OW"
        DROP_MESSAGE="$DROP_MESSAGE <br>$FULL_DEST_FILE already exists for OW - not copied again."
        HIDDEN_MESSAGE="$HIDDEN_MESSAGE; ((('cp -n $FULL_RSIND_FILE_NAME $DESTDIR' failed))); "
        if [ $EXIT_STATUS = 0 ] ; then
            EXIT_STATUS=2
        fi
    elif cp -n "$FULL_RSIND_FILE_NAME" $DESTDIR ; then
        DROP_MESSAGE="$DROP_MESSAGE <br>$RSIND_FILE_NAME ($NUM_ROWS_IN_NEW_RSIND_FILE rows) copied successfully for OW"
        if [ $STATUS_GetMostRecentVersion -eq 0 ] ; then
            DROP_MESSAGE="$DROP_MESSAGE <br>   --Replacing $EXISTING_RSIND_FILE ($EXISTING_RSIND_SIZE rows)"
        else
            DROP_MESSAGE="$DROP_MESSAGE <br>   --(There was no prior RSIND file.)"
        fi
       HIDDEN_MESSAGE="$HIDDEN_MESSAGE; (((Copied to $DESTDIR for OW)))"
    else
        USER_MESSAGE="$USER_MESSAGE; Failed to cp for OW"
        HIDDEN_MESSAGE="$HIDDEN_MESSAGE; ((('cp -n $FULL_RSIND_FILE_NAME $DESTDIR' failed)))"
        EXIT_STATUS=1
    fi
else
    DROP_MESSAGE="$DROP_MESSAGE <br>$RSIND_FILE_NAME ($NUM_ROWS_IN_NEW_RSIND_FILE rows) NOT copied for OW"
    DROP_MESSAGE="$DROP_MESSAGE <br>  (OW season over or the uploaded RSIND file appears to be for next season.)"
fi



#####
#####  Done!
#####

echo $USER_MESSAGE
echo "[[[$DROP_MESSAGE $WARNING_STRINGS]]]"
echo $HIDDEN_MESSAGE
exit $EXIT_STATUS
